name: Deploy to Firebase Hosting on push to master
'on':
  push:
    branches:
      - master

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Additional steps for building/testing your application can go here.
      # For example, installing dependencies, running tests, building your application, etc.

      # Use Firebase CLI to deploy to a specific channel
      - name: Firebase Deploy to Channel
        run: |
          npm install -g firebase-tools
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DB_DYNAMIC_COMMENTS }}" | firebase login:ci
          firebase hosting:channel:deploy your-channel-id --expires 7d --project db-dynamic-comments --json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
